name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


env:
  APP_NAME: mirror

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish-github-release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: 下载构建产物
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          name: "^${{ env.APP_NAME }}.*"
          name_is_regexp: true
          skip_unpack: true

      - name: 上传主程序 Release
        if: ${{ steps.get-tag.outputs.puniyu_tag }}
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: ${{ env.APP_NAME }}-*
          tag_name: ${{ steps.get-tag.outputs.puniyu_tag }}
